server:
  port: 5050
  servlet:
    context-path: /api
    session:
      timeout: PT60M
spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/easychat?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
project:
  folder: D:/Develop/Project/Log/kkk/
log:
  root:
    level: debug
ws:
  port: 5051
admin:
  email: test@qq.com
dev: false
